edition = "2018"

max_width = 80
array_width = 50
indent_style = "Block"
reorder_imports = false
reorder_modules = false
merge_derives = false
use_small_heuristics = "Max"

error_on_line_overflow = true
error_on_unformatted = true

ignore = []
