[package]
name = "frontend-yew"
version = "0.1.0"
authors = ["zzy <9809920@qq.com>"]
edition = "2018"

[dependencies]
yew = "0.18.0"
yew-router = "0.15.0"

wasm-bindgen = "0.2.74"

serde = { version = "1.0.126", features = ["derive"] }
anyhow = "1.0.40"
